version: "3.8"

volumes:
  el_database:
  legacy_node_modules:
  node_modules:

services:
  backend:
    volumes:
      - ./backend:/usr/src/backend
    depends_on:
      - db
    build:
      context: ./backend
    ports:
      - 3000:3000

  frontend:
    volumes:
      - ./frontend:/usr/src/frontend
      - node_modules:/usr/src/frontend/node_modules
    # depends_on:
    #   - backend
    build:
      context: ./frontend
    ports:
      - 3030:3000

  # legacy:
  #   depends_on:
  #     - db
  #   volumes:
  #     - ./legacy:/usr/src/legacy
  #     - legacy_node_modules:/usr/src/legacy/node_modules
  #   build:
  #     context: ./legacy
  #   command: exit
  #   ports:
  #     - 3333:3000
  #   # entrypoint: npm run dev

  db:
    image: postgres:12
    environment:
      - POSTGRES_PASSWORD=ohb
    volumes:
      - el_database:/var/lib/postgresql/data

  pgweb:
    image: sosedoff/pgweb
    depends_on:
      - db
    ports:
      - 8081:8081
    environment:
      - DATABASE_URL=postgres://postgres:ohb@db:5432/one_hour_beats?sslmode=disable
