version: "3.8"

volumes:
  node_modules:

services:
  frontend:
    volumes:
      - /var/www/html:/usr/src/frontend/build
      - node_modules:/usr/src/frontend/node_modules
    build:
      context: ./frontend
    tty: true
